version: '3'

services:
  db:
    image: postgres:15.3
    container_name: invoice-condu-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pdAdmin:
    image: dpage/pgadmin4
    container_name: invoice-condu-pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@mail.co
      - PGADMIN_DEFAULT_PASSWORD=0123960
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json